"""user_confirm

Revision ID: 0577090c44ec
Revises: 7c6f0254cff7
Create Date: 2016-09-30 13:09:34.717475

"""

# revision identifiers, used by Alembic.
revision = '0577090c44ec'
down_revision = '7c6f0254cff7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
