"""8b

Revision ID: 7c6f0254cff7
Revises: 3af2123fca95
Create Date: 2016-09-30 02:24:16.370283

"""

# revision identifiers, used by Alembic.
revision = '7c6f0254cff7'
down_revision = '3af2123fca95'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
